# Generated by Django 4.1.6 on 2023-02-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='buy1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=40)),
                ('pprize', models.IntegerField()),
                ('pdes', models.CharField(max_length=100)),
                ('pimage', models.ImageField(upload_to='')),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
