# Generated by Django 4.1.6 on 2023-02-17 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_buy1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy1',
            name='pimage',
        ),
    ]
