# Generated by Django 4.1.6 on 2023-02-18 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_buy1_pimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='customercardpay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardname', models.CharField(max_length=30)),
                ('cardnumber', models.CharField(max_length=30)),
                ('cardexpiry', models.CharField(max_length=30)),
                ('securitycode', models.CharField(max_length=30)),
            ],
        ),
    ]
