# Generated by Django 4.1.6 on 2023-02-18 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_customercardpay'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='customercardpay',
            new_name='customercard',
        ),
    ]
