# Generated by Django 4.1.6 on 2023-02-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_customercardpay_customercard'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='shopid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
